---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trade-query
  namespace: mu-architecture-demo
  labels:
    name: trade-query
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trade-query
    spec:
      hostAliases:
      - ip: "{{HOSTIPADDRESS}}"
        hostnames:
        - "{{HBASECONTAINERID}}"
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: dineshpillai/imcs-tradequeryservice:0.0.1-SNAPSHOT
        name: trade-query
        imagePullPolicy: Always
        ports:
        - name: price-streamer
          containerPort: 8094
        env:
        - name: spring_cloud_zookeeper_connectString
          value: zoo1:2181
        resources: {}


---
apiVersion: v1
kind: Service
metadata:
  name: trade-query-service
  namespace: mu-architecture-demo
  labels:
    app: trade-query
spec:
  ports:
  - port: 8094
    name: trade-query-port
    targetPort: 8094
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: position-query
  labels:
    app: position-query
  namespace: default
data:
  application.yml: |-
    endpoints.trace.sensitive: false

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: position-query
  namespace: mu-architecture-demo
  labels:
    name: position-query
spec:
  replicas: 2
  template:
    metadata:
     name: position-query 
     labels:
        name: position-query
    spec:
      hostAliases:
      - ip: "{{HOSTIPADDRESS}}"
        hostnames:
        - "{{HBASECONTAINERID}}"
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: dineshpillai/imcs-positionqueryservice:0.0.1-SNAPSHOT
        name: position-query
        imagePullPolicy: Always
        ports:
        - containerPort: 8093
        env:
        - name: requireHz
          value: "false"
        resources: {}
      nodeSelector:
        beta.kubernetes.io/os: linux


---
apiVersion: v1
kind: Service
metadata:
  name: position-query
  namespace: mu-architecture-demo
  labels:
    app: position-query
spec:
  ports:
  - port: 8093
    targetPort: 8093
    nodePort: 31093
  type: NodePort
  selector:
    app: position-query